spyder-ide/spyder-vim

spyder_vim/vim_widget.py

Implemented 'change word'. I simply used dw + i. I'm assuming repeat is not used here? Seems to work fine here.

Implement cw (as dw + i)

---

spyder_vim/vim_widget.py

b [go to beginning of previous word]

PR: new b command

---

spyder_vim/vim_widget.py

^ [Moves cursor to first non-whitespace character on the current line]

PR: Added command ^

---

spyder_vim/vim_widget.py

f[move to a character forwards from current cursor position]
F[move to a character backwards from current cursor position]

PR: Added commands f and F

---

spyder_vim/tests/test_vim.py
spyder_vim/vim_widget.py

Implementation of x command along with test.

PR: Command x to delete character under cursor

---

spyder_vim/tests/test_vim.py
spyder_vim/vim.py

Updated plugin to work with Spyder 4, fixes #43

PR: Update plugin to work with Spyder 4

---

spyder_vim/tests/test_vim.py
spyder_vim/vim_widget.py

Fixed copy and past cursor position behavior.
Fixed char selection to include the character under the cursor like in Vim.

PR: Fix copy/past cursor behavior

---

spyder_vim/tests/test_vim.py
spyder_vim/vim_widget.py

Fixes : #48 
By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.
I certify the above statement is true and correct: ok97465

PR:Fix behavior of dw command

---

spyder_vim/tests/test_vim.py
spyder_vim/vim_widget.py

@goanpeca  I'm working on fixing the behavior of the deletion commands (d, dd, x etc...). Thanks, @ok97465 for the dw command.

PR: Fix deletion behavior

---

spyder_vim/tests/test_vim.py
spyder_vim/vim_widget.py

Added forward (/) and backward (?) search commands.
Added n and N commands to move the cursor to next and previous occurrence.

PR: Add search commands

---

spyder_vim/tests/test_vim.py
spyder_vim/vim_widget.py

Fixed issue #53 and added tests for regex backward and forward search.
Fixes #53

PR: Fix regex search

---

spyder_vim/tests/test_vim.py
spyder_vim/vim_widget.py

add gt, gT command to move around tabs of editor

Add gt, gT command

---

spyder_vim/vim_widget.py

Fixed the cursor decorator that is not clearing when switching to insert mode.

PR: Fix cursor decorator

---

spyder_vim/tests/test_vim.py
spyder_vim/vim_widget.py

Added basic vim registers:
* Numbered registers
* Small delete register
* Normal register with lowercase letters
* Append to normal registers with uppercase letters

PR: Add registers

---

spyder_vim/tests/test_vim.py
spyder_vim/vim_widget.py

Added the % command to go to the matching bracket.

PR: Add % command

---

spyder_vim/tests/test_vim.py
spyder_vim/vim_widget.py

* Fixed #66 cw command.
* Added cc command.

PR: Fix c commands

---

spyder_vim/vim_widget.py

PR: Fix position after D command

---

spyder_vim/tests/test_vim.py
spyder_vim/vim_widget.py

- ~ command
- 5~ command
- ~command in visual mode

PR: Add ~ command

---

spyder_vim/tests/test_vim.py
spyder_vim/vim_widget.py

- <<, >> command
- 6<<, 6>> command
- <,> command in visual mode

Add <<, >> command

---

README.md

Also improve installation instructions a bit.
Fixes #40.

PR: Add "Usage" section to Readme

---

requirements/tests.txt

PR: Fix tests
